version: '2'
services:
  db:
    image: postgres
    volumes:
      - postgres_app:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
  app:
    restart: always
    build: ./app/
    command: bash -c "npm run start"
    ports:
      - "4000:4000"
    depends_on:
      - api
    env_file:
      - .env
  api:
    build: .
    command: bash -c "echo yes | python manage.py collectstatic && python manage.py makemigrations && python manage.py migrate && gunicorn --workers=3 --timeout=120 -k gevent --log-level=DEBUG config.wsgi -b 0.0.0.0:8000"
    volumes:
      - .:/project
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - .env
  nginx:
    image: nginx:latest
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - .:/project
    depends_on:
      - api
volumes:
  postgres_app: